# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9d841eaf48b522444b5e779e25300f0ac4fbd1b57bb879716970eba71d67418fe3db843327b9a32f60929067406535e490f0fa18b567da20d07c3e5e390653

test:
  secret_key_base: b21da35fa1270b3802fe7a789092d160199ae14699e50907e48a999f1470cff74b4d2a2497b20d29e672f1c72e1cff4219f961a06fb1bc58d50f82583fee4283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
